#!/bin/python3

n = input("Enter the number : ") 
sum = 0
try:
    int(n)
    for e in n:
        try:
            sum += int(e);
        except:
            pass
    sum = sum if int(n) > 0 else -(sum)
    print("Sum of digits of", n, "is :", sum)

except :
    print("Not an integer!")
